version: "3"

networks:
  devnet:
services:
  # apache
    apache:
      container_name: apache
      build:
        context: ./docker/${PHP_VER}
        dockerfile: Dockerfile
      image: "http:alpine"
      ports:
        - "${APP_PORT}:80"
      volumes:
        - ${APP_PATH}:${DOCUMENT_ROOT}
      depends_on:
        - database
      networks:
       - devnet
  # node
    node:
      build:
        context: ./docker/node
        dockerfile: Dockerfile
      image: gmir/docker-node:latest
      volumes:
        - ${APP_PATH}:${DOCUMENT_ROOT}
      networks:
        - devnet
  # mysql
    database:
      image: mysql:5.7.29
      container_name: database
      restart: unless-stopped
      tty: true
      ports:
        - "${DB_PORT}:3306"
      environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      networks:
        - devnet
  # phpmyadmin
    phpmyadmin:
      depends_on:
        - database
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '8888:80'
      environment:
        PMA_HOST: database
        MYSQL_ROOT_PASSWORD: secret
      networks:
        - devnet

    solr:
      image: "solr:6.6.6"
      ports:
        - "8983:8983"
      volumes:
        - ./docker/solr/impoqo:/opt/solr/server/solr/mycores/
      entrypoint:
        - bash
        - "-c"
        - "precreate-core impoqo; exec solr -f"

volumes:
    db_data:
